// src/lib/components/stars.svelte
<script lang="ts">
  type Star = {
    background: string;
    left: string;
    top: string;
    radius: string;
    containerRadius?: string;
    animation?: string;
  };
  const randInt = (i: number) => Math.round(Math.random() * i);
  const randomRgba = (alpha: number) => {
    return `rgba(${randInt(255)}, ${randInt(255)}, ${randInt(255)}, ${alpha})`;
  };
  const star = (): Star => {
    const r = Math.floor(0.1 + Math.random() * 1337);
    let containerRadius = undefined;
    let animation = undefined;
    if (Math.random() < 0.3) {
      containerRadius = `${r}px`;
      const a = Math.random() > 0.5 ? "spinner" : "spinner-reverse";
      const duration = Math.floor(r) / 100;
      animation = `${a} ${duration}s linear infinite`;
    }
    const radius = `${randInt(7)}px`;
    const x = randInt(100),
      y = randInt(100);
    return {
      background: `radial-gradient(circle, ${randomRgba(0.6)} 0%, ${randomRgba(0)} 100%)`,
      left: `${x}%`,
      top: `${y}%`,
      radius: radius,
      containerRadius: containerRadius,
      animation: animation
    };
  };
  const stars: Star[] = Array.from({ length: 400 }).map(star);
</script>

<div class="absolute w-screen h-screen overflow-hidden">
  {#each stars as star}
    {#if star.containerRadius}
      <div
        class="absolute z-10 max-w-full max-h-full"
        style="width: {star.containerRadius}; height: {star.containerRadius}; animation: {star.animation}; top: {star.top}; left: {star.left}"
      >
        <div
          class="absolute z-10"
          style="width: {star.radius}; height: {star.radius}; background: {star.background};"
        ></div>
      </div>
    {:else}
      <div
        class="absolute z-10"
        style="width: {star.radius}; height: {star.radius}; background: {star.background}; top: {star.top}; left: {star.left};"
      ></div>
    {/if}
  {/each}
</div>

// src/components/stars.tsx
import { CSSProperties } from "react";

type Props = {
  count: number;
};


type StarProps = {
  key: number
  solo?: boolean;
}

const Star = ({ key, solo }: StarProps) => {
  const randomRgba = (alpha: number) => {
    return `rgba(${Math.random() * 255}, ${Math.random() * 255}, ${Math.random() * 255}, ${alpha})`
  }
  const radius = `${Math.random() * 7}px`
  let style: CSSProperties = {
    background: `radial-gradient(circle, ${randomRgba(0.6)} 0%, ${randomRgba(0)} 100%)`,
    width: radius,
    height: radius,
  };
  if (solo) {
    const x = Math.floor(Math.random() * 100), y = Math.floor(Math.random() * 100);
    style = {
      ...style,
      left: `${x}%`,
      top: `${y}%`
    }
  }
  return (
    <div
      key={key}
      style={style}
      className="absolute z-10">
    </div>
  )
}

const SpinningStar = ({ key }: StarProps) => {
  const r = .1 + Math.random() * 1337
  const containerRadius = `${r}px`
  const duration = Math.floor(r) / 100;
  const x = Math.floor(Math.random() * 100), y = Math.floor(Math.random() * 100);
  const animation = Math.random() > .5 ? "spinner" : "spinner-reverse"
  return (
    <div
      key={key}
      style={{
        left: `${x}%`,
        top: `${y}%`,
        width: containerRadius,
        height: containerRadius,
        animation: `${animation} ${duration}s linear infinite`
      }}
      className="absolute z-10 max-w-full max-h-full">
      <Star key={-1} />
    </div>
  )
}
const Stars = ({ count }: Props) => {
  return (
    <div className="absolute w-screen h-screen overflow-hidden">
      {Array.from({ length: count }).map((_it, i) => {
        return i % 4 === 0 ? <SpinningStar key={i} /> : <Star key={i} solo={true} />
      })}
    </div>
  );
};

export default Stars;
