// src/app/components/navbar.tsx
"use client"
import Link from "next/link";
import { usePathname } from "next/navigation";

const Navbar = () => {
  const path = usePathname()
  const link = (text: string, href: string) => {
    return (
      <Link data-selected={path === href} className="gradient w-full h-max rounded-md border-2" aria-label={text} href={href}>
        <div className="btn">
          {text}
        </div>
      </Link>
    )
  }
  return (
    <div className="w-max h-max px-6 py-2 mx-auto rounded-full bg-slate-900 grid place-content-center">
      <div className="flex flex-row gap-6">
        {link("Home", "/")}
        {link("Cases", "/cases")}
        {link("Contact", "/contact")}
      </div>
    </div>
  )
}


export default Navbar

// src/lib/components/navbar.svelte
<nav class="h-max flex flex-row justify-between w-full z-50 p-3 lg:p-12">
  <a class="text-md lg:text-2xl font-bold z-50" aria-label="home" href="/">
    <span class="text-center">[idimitrov.dev]</span>
  </a>
  <a
    class="w-max px-4 py-1 lg:px-10 rounded-full border-[1px] border-amber-50 z-50"
    aria-label="contact"
    href="/contact"
  >
    <span class="text-center">Contact</span>
  </a>
</nav>
